# Generated by Django 5.1.5 on 2025-01-17 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCCComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'LCC Competition',
                'verbose_name_plural': 'LCC Competitions',
            },
        ),
        migrations.AlterModelOptions(
            name='lcccreator',
            options={'verbose_name': 'LCC Creator', 'verbose_name_plural': 'LCC Creators'},
        ),
        migrations.AlterModelOptions(
            name='lccentry',
            options={'verbose_name': 'LCC Entry', 'verbose_name_plural': 'LCC Entries'},
        ),
        migrations.AlterField(
            model_name='lccentry',
            name='competition_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_name', to='lcc_entries.lcccomp', to_field='name'),
        ),
        migrations.AlterField(
            model_name='lccentry',
            name='competition_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_year', to='lcc_entries.lcccomp', to_field='year'),
        ),
    ]
