# Generated by Django 5.1.5 on 2025-01-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0003_alter_lccentry_competition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lccentry',
            name='competition_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_name', to='lcc_entries.lcccomp', to_field='name'),
        ),
        migrations.AlterField(
            model_name='lccentry',
            name='competition_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_year', to='lcc_entries.lcccomp', to_field='year'),
        ),
    ]
