# Generated by Django 5.1.5 on 2025-01-17 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0004_alter_lccentry_competition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lccentry',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lcc_entries.lcccreator'),
        ),
    ]
