# Generated by Django 5.1.5 on 2025-01-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0007_alter_lcccomp_name_alter_lcccomp_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lccentry',
            name='competition_year',
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
