# Generated by Django 5.1.5 on 2025-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0011_alter_lcccomp_name_alter_lcccomp_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcccomp',
            name='name',
            field=models.CharField(choices=[('LCC', 'LCC'), (2004, 'LCC 2.5'), (2005, 'LCC III'), (2005, 'LCC IV'), (2007, 'LCC V'), (2008, 'LCC VI'), (2009, 'LCC VII'), (2010, 'LCC VIII'), (2011, 'LCC IX'), (2012, 'LCC X'), (2013, 'LCC XI'), (2014, 'LCC XII'), (2015, 'LCC 2015'), (2016, 'LCC 2016'), (2017, 'LCC 2017'), (2018, 'LCC 2018'), (2019, 'SaberComp 2019'), (2020, 'SaberComp 2020'), (2021, 'SaberComp 2021'), (2022, 'SaberComp 2022'), (2023, 'SaberComp 2023'), (2024, 'SaberComp 2024')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='year',
            field=models.IntegerField(choices=[(2002, 2002), (2004, 'LCC 2.5'), (2005, 'LCC III'), (2005, 'LCC IV'), (2007, 'LCC V'), (2008, 'LCC VI'), (2009, 'LCC VII'), (2010, 'LCC VIII'), (2011, 'LCC IX'), (2012, 'LCC X'), (2013, 'LCC XI'), (2014, 'LCC XII'), (2015, 'LCC 2015'), (2016, 'LCC 2016'), (2017, 'LCC 2017'), (2018, 'LCC 2018'), (2019, 'SaberComp 2019'), (2020, 'SaberComp 2020'), (2021, 'SaberComp 2021'), (2022, 'SaberComp 2022'), (2023, 'SaberComp 2023'), (2024, 'SaberComp 2024')], unique=True),
        ),
    ]
