# Generated by Django 5.1.5 on 2025-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0014_alter_lcccomp_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcccomp',
            name='name',
            field=models.CharField(choices=[('LCC', 'LCC'), ('LCC 2.5', 'LCC 2.5'), ('LCC III', 'LCC III'), ('LCC IV', 'LCC IV'), ('LCC V', 'LCC V'), ('LCC VI', 'LCC VI'), ('LCC VII', 'LCC VII'), ('LCC VIII', 'LCC VIII'), ('LCC IX', 'LCC IX'), ('LCC X', 'LCC X'), ('LCC XI', 'LCC XI'), ('LCC XII', 'LCC XII'), ('LCC 2015', 'LCC 2015'), ('LCC 2016', 'LCC 2016'), ('LCC 2017', 'LCC 2017'), ('LCC 2018', 'LCC 2018'), ('SaberComp 2019', 'SaberComp 2019'), ('SaberComp 2020', 'SaberComp 2020'), ('SaberComp 2021', 'SaberComp 2021'), ('SaberComp 2022', 'SaberComp 2022'), ('SaberComp 2023', 'SaberComp 2023'), ('SaberComp 2024', 'SaberComp 2024')], max_length=200, unique=True),
        ),
    ]
