# Generated by Django 5.1.5 on 2025-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0016_alter_lcccomp_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcccomp',
            name='announcment_promo',
            field=models.URLField(default='http://'),
        ),
        migrations.AddField(
            model_name='lcccomp',
            name='end_date',
            field=models.DateField(default='1977-05-25'),
        ),
        migrations.AddField(
            model_name='lcccomp',
            name='live_judging',
            field=models.URLField(default='http://'),
        ),
        migrations.AddField(
            model_name='lcccomp',
            name='rules',
            field=models.TextField(default='No rules.', max_length=2000),
        ),
        migrations.AddField(
            model_name='lcccomp',
            name='start_date',
            field=models.DateField(default='1977-05-25'),
        ),
        migrations.AddField(
            model_name='lcccomp',
            name='theme',
            field=models.CharField(default='Theme', max_length=200),
        ),
    ]
