# Generated by Django 5.1.5 on 2025-01-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0017_lcccomp_announcment_promo_lcccomp_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcccomp',
            name='theme',
            field=models.CharField(blank=True, default='Theme', max_length=200, null=True),
        ),
    ]
