# Generated by Django 5.1.5 on 2025-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0018_alter_lcccomp_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcccomp',
            name='announcment_promo',
            field=models.URLField(blank=True, default='http://', null=True),
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='live_judging',
            field=models.URLField(blank=True, default='http://', null=True),
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='rules',
            field=models.TextField(default='No rules. (This is a default value)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
