# Generated by Django 5.1.5 on 2025-01-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0019_alter_lcccomp_announcment_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcccomp',
            name='highlight_reel',
            field=models.URLField(blank=True, default='http://', null=True),
        ),
    ]
