# Generated by Django 5.1.5 on 2025-01-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0020_lcccomp_highlight_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lccentry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Disqualified', 'Disqualified'), ('Withdrawn', 'Withdrawn'), ('Live', 'Live')], default='Pending Review', max_length=200),
        ),
        migrations.AddField(
            model_name='lccentry',
            name='top_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='end_date',
            field=models.DateField(default='2020-12-31'),
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='start_date',
            field=models.DateField(default='2020-05-04'),
        ),
    ]
