# Generated by Django 5.1.5 on 2025-01-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0023_alter_lcccomp_name_alter_lcccomp_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcccomp',
            name='year',
            field=models.CharField(choices=[('Lightsaber Choreography Competition', 'Lightsaber Choreography Competition'), ('Lightsaber Choreography Competition 2.5', 'Lightsaber Choreography Competition 2.5'), ('Lightsaber Choreography Contest III', 'Lightsaber Choreography Contest III'), ('Lightsaber Choreography Competition IV', 'Lightsaber Choreography Competition IV'), ('Lightsaber Choreography Contest V', 'Lightsaber Choreography Contest V'), ('Lightsaber Choreography Contest VI', 'Lightsaber Choreography Contest VI'), ('Lightsaber Choreography Contest VII', 'Lightsaber Choreography Contest VII'), ('Lightsaber Choreography Competition VIII', 'Lightsaber Choreography Competition VIII'), ('Lightsaber Choreography Competition IX', 'Lightsaber Choreography Competition IX'), ('Lightsaber Choreography Competition X', 'Lightsaber Choreography Competition X'), ('Lightsaber Choreography Contest XI', 'Lightsaber Choreography Contest XI'), ('Lightsaber Choreography Contest XII', 'Lightsaber Choreography Contest XII'), ('Lightsaber Choreography Contest 2015', 'Lightsaber Choreography Contest 2015'), ('Lightsaber Choreography Competition 2016', 'Lightsaber Choreography Competition 2016'), ('Lightsaber Choreography Competition 2017', 'Lightsaber Choreography Competition 2017'), ('Lightsaber Choreography Competition 2018', 'Lightsaber Choreography Competition 2018'), ('SaberComp 2019', 'SaberComp 2019'), ('SaberComp 2020', 'SaberComp 2020'), ('SaberComp 2021', 'SaberComp 2021'), ('SaberComp 2022', 'SaberComp 2022'), ('SaberComp 2023', 'SaberComp 2023'), ('SaberComp 2024', 'SaberComp 2024')], max_length=40),
        ),
    ]
