# Generated by Django 5.1.5 on 2025-01-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0026_alter_lcccomp_name_alter_lcccomp_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcccomp',
            name='year',
            field=models.CharField(choices=[('LCC1', 2002), ('LCC2', 2004), ('LCC3', 2004), ('LCC4', 2005), ('LCC5', 2007), ('LCC6', 2008), ('LCC7', 2009), ('LCC8', 2010), ('LCC9', 2011), ('LCC10', 2012), ('LCC11', 2013), ('LCC12', 2014), ('LCC2015', 2015), ('LCC2016', 2016), ('LCC2017', 2017), ('LCC2018', 2018), ('SC19', 2019), ('SC20', 2020), ('SC21', 2021), ('SC22', 2022), ('SC23', 2023), ('SC24', 2024)], max_length=200, unique=True),
        ),
    ]
