# Generated by Django 5.1.5 on 2025-01-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0028_alter_lcccomp_name_alter_lcccomp_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lccentry',
            name='competition_year',
            field=models.ForeignKey(default='2002', on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_year', to='lcc_entries.lcccomp', to_field='year'),
        ),
        migrations.AlterField(
            model_name='lccentry',
            name='competition_name',
            field=models.ForeignKey(default='LCC', on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_name', to='lcc_entries.lcccomp', to_field='name'),
        ),
    ]
