# Generated by Django 5.1.5 on 2025-01-22 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0030_lccentry_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lccentry',
            name='competition_year',
        ),
        migrations.RemoveField(
            model_name='lccentry',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='year',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='lccentry',
            name='competition_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_name', to='lcc_entries.lcccomp', to_field='name'),
        ),
    ]
