# Generated by Django 5.1.5 on 2025-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0031_remove_lccentry_competition_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lccentry',
            name='content_type',
            field=models.CharField(choices=[('LCC-SC', 'Official Entry'), ('Special', 'Special Edition'), ('Supp', 'Supplemental'), ('Promo', 'Official Promo'), ('Highlight', 'Highlight Reel'), ('Other', 'Other')], default='LCC-SC', max_length=200),
        ),
    ]
