# Generated by Django 5.1.5 on 2025-01-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0033_lccentry_competition_year_alter_lcccomp_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lccentry',
            name='competition_year',
        ),
    ]
