# Generated by Django 5.1.5 on 2025-01-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0034_remove_lccentry_competition_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcccomp',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
