# Generated by Django 5.1.5 on 2025-01-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0035_alter_lcccomp_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lcccomp',
            name='end_date',
        ),
        migrations.AddField(
            model_name='lcccomp',
            name='deadline',
            field=models.DateField(default='2021-01-31'),
        ),
        migrations.AddField(
            model_name='lcccomp',
            name='open_submissions',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
