# Generated by Django 5.1.5 on 2025-01-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0039_lccentry_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Crew Role',
                'verbose_name_plural': 'Crew Roles',
            },
        ),
        migrations.CreateModel(
            name='LCCCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='lcc_entries.lcccreator')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AddField(
            model_name='lccentry',
            name='company_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lcc_entries.lcccompany'),
        ),
    ]
