# Generated by Django 5.1.5 on 2025-01-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0040_crewrole_lcccompany_lccentry_company_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='lccentry',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='entries', to='lcc_entries.crewrole'),
        ),
    ]
