# Generated by Django 5.1.5 on 2025-01-27 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0041_lccentry_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lccentry',
            name='crew',
        ),
        migrations.AddField(
            model_name='lccentry',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lcc_entries.crewrole'),
        ),
    ]
