# Generated by Django 5.1.5 on 2025-01-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0042_remove_lccentry_crew_lccentry_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lccentry',
            name='crew',
        ),
    ]
