# Generated by Django 5.1.5 on 2025-01-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0043_remove_lccentry_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcccomp',
            name='announcment_promo',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='highlight_reel',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lcccomp',
            name='live_judging',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
