# Generated by Django 5.1.5 on 2025-02-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0044_alter_lcccomp_announcment_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcccreator',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
