# Generated by Django 5.1.5 on 2025-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc_entries', '0045_lcccreator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcccompany',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
